version: "3.7"
services:
    postgres_cadastro:
        container_name: postgres_extracao
        image: postgres:12.2
        command: tail -F anything
        environment:
            POSTGRES_USER: extracao
            POSTGRES_PASSWORD: extracao
        ports:
            - "5432:5432"
        networks:
        networks:
            external: true
            name: network-extracao            
    postgres_site:
        container_name: postgres_site
        image: postgres:12.2
        command: tail -F anything
        environment:
            POSTGRES_USER: site
            POSTGRES_PASSWORD: site
        ports:
            - "5422:5432"
        networks:
            external: true
            name: network-site
    keycloak_ifood:
        container_name: keycloak_tcc
        image: quay.io/keycloak/keycloak:11.0.1
        command: tail -F anything
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
        ports:
            - "8180:8080"
    jaeger_ifood:
        container_name: jaeger_tcc
        image: jaegertracing/all-in-one:1.19
        command: tail -F anything
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "14250:14250"
            - "9411:9411"