version: "3.3"
services:
    postgres_cadastro:
        container_name: postgres_extracao
        image: postgres:12.2
        restart: always
        environment:
            POSTGRES_USER: extracao
            POSTGRES_PASSWORD: extracao
            POSTGRES_DB: postegres
        ports:
            - "5432:5432"
        networks:
            - network-extracao            
    postgres_site:
        container_name: postgres_site
        image: postgres:12.2
        restart: always
        environment:
            POSTGRES_USER: site
            POSTGRES_PASSWORD: site
            POSTGRES_DB: postegres
        ports:
            - "5422:5432"
        networks:
            - network-site
    keycloak_ifood:
        container_name: keycloak_tcc
        image: quay.io/keycloak/keycloak:11.0.1
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
        ports:
            - "8180:8080"
    jaeger_ifood:
        container_name: jaeger_tcc
        image: jaegertracing/all-in-one:1.19
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "14250:14250"
            - "9411:9411"
    site-service: 
        image: quarkus/site-tcc-jvm
        build: 
            context: ./site
            dockerfile: src/main/docker/Dockerfile.multistage
        environment:
            QUARKUS_DATASOURCE_URL: jdbc:postgresql://postgres_site:5432/postgres
        ports:
            - "8080:8080" #specify ports forewarding
        depends_on:
            - postgres_site
        networks:
            - network-site 
networks:
    network-extracao:
        driver: bridge
    network-site:
        driver: bridge