CREATE TABLE "RELACAO_POSTAGEM_NORMA" (
    "cd_post" INT   NOT NULL,
    "cd_norm" INT   NOT NULL,
    CONSTRAINT "pk_RELACAO_POSTAGEM_NORMA" PRIMARY KEY (
        "cd_post","cd_norm"
     )
);

COMMENT ON COLUMN "RELACAO_POSTAGEM_NORMA".cd_post IS 'Código identificador do post.';
COMMENT ON COLUMN "RELACAO_POSTAGEM_NORMA".cd_norm IS 'Código identificador da norma.';

ALTER TABLE "RELACAO_POSTAGEM_NORMA" ADD CONSTRAINT "fk_RELACAO_POSTAGEM_NORMA_cd_post" FOREIGN KEY("cd_post")
REFERENCES "POSTAGEM" ("cd_post");

ALTER TABLE "RELACAO_POSTAGEM_NORMA" ADD CONSTRAINT "fk_RELACAO_POSTAGEM_NORMA_cd_norm" FOREIGN KEY("cd_norm")
REFERENCES "NORMA" ("cd_norm");