CREATE TABLE "RELACAO_POSTAGEM_CATEGORIA" (
    "cd_post" INT   NOT NULL,
    "cd_cat" SMALLINT   NOT NULL,
    CONSTRAINT "pk_RELACAO_POSTAGEM_CATEGORIA" PRIMARY KEY (
        "cd_post","cd_cat"
     )
);

COMMENT ON COLUMN "RELACAO_POSTAGEM_CATEGORIA".cd_post IS 'Código identificador da postagem.';
COMMENT ON COLUMN "RELACAO_POSTAGEM_CATEGORIA".cd_cat IS 'Código identificador da categoria.';

ALTER TABLE "RELACAO_POSTAGEM_CATEGORIA" ADD CONSTRAINT "fk_RELACAO_POSTAGEM_CATEGORIA_cd_post" FOREIGN KEY("cd_post")
REFERENCES "POSTAGEM" ("cd_post");

ALTER TABLE "RELACAO_POSTAGEM_CATEGORIA" ADD CONSTRAINT "fk_RELACAO_POSTAGEM_CATEGORIA_cd_cat" FOREIGN KEY("cd_cat")
REFERENCES "DOMINIO_CATEGORIA" ("cd_cat");